project_name = "sreboot"
region = "us-central1"
zone = "us-central1-a"
cred_file = "/home/shakeer/sreboot-7d764dbc5ba3.json"
#cred_file = "sreboot-6be81213cd05.json"
network_name = "terraform-sreboot"
