pipeline {

  agent any

  environment {
    SVC_ACCOUNT_KEY = credentials('sreboot')
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
        sh 'mkdir -p creds' 
        sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./creds/serviceaccount.json'
      }
    }

    stage('State File Copy') {
      steps {
          sh 'cd TERRAFORM/GCEinstance ; terraform init'
          sh 'cd TERRAFORM/GCEinstance ; terraform plan -out myplan'
        }
    }

    stage('Approval') {
      steps {
        script {
          def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
        }
      }
    }

    stage('TF Apply') {
      steps {
          sh 'cd TERRAFORM/GCEinstance ;terraform apply -input=false myplan'
        }
      }

  } 

}
